spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-postgres
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
    connection-properties: 'serverTimezone=UTC'

  jpa:
    hibernate:
      ddl-auto: update # Use "update" for development; use "validate" or "none" for production
#    show-sql: true # Shows generated SQL in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL dialect

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE